# Generated by Django 4.1.2 on 2022-10-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppLfcargos',
            fields=[
                ('ch_key', models.IntegerField(primary_key=True, serialize=False)),
                ('ch_desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'app_lfcargos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppLfcertificados',
            fields=[
                ('cer_key', models.IntegerField(primary_key=True, serialize=False)),
                ('cer_desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'app_lfcertificados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppLfempcer',
            fields=[
                ('ec_key', models.IntegerField(primary_key=True, serialize=False)),
                ('ec_fk_emp_key', models.IntegerField(blank=True, null=True)),
                ('ec_fk_cer_key', models.IntegerField(blank=True, null=True)),
                ('ec_exp_yyyymmdd', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'app_lfempcer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppLfemployees',
            fields=[
                ('emp_key', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(blank=True, max_length=70, null=True)),
                ('emp_fk_ch_key', models.IntegerField(blank=True, null=True)),
                ('emp_email', models.CharField(blank=True, max_length=80, null=True)),
                ('emp_phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'app_lfemployees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppLfphotos',
            fields=[
                ('ph_key', models.IntegerField(primary_key=True, serialize=False)),
                ('ph_fk_rep_key', models.IntegerField(blank=True, null=True)),
                ('ph_link', models.CharField(blank=True, max_length=65535, null=True)),
                ('ph_yyyymmdd', models.CharField(blank=True, max_length=50, null=True)),
                ('ph_desc', models.CharField(blank=True, max_length=65535, null=True)),
                ('ph_user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ph_obs', models.CharField(blank=True, max_length=65535, null=True)),
            ],
            options={
                'db_table': 'app_lfphotos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppLfphotos2',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ph_key2', models.IntegerField(blank=True, null=True)),
                ('ph_fk_rep_key2', models.IntegerField(blank=True, null=True)),
                ('ph_fk_ph_key', models.IntegerField(blank=True, null=True)),
                ('ph_link2', models.CharField(blank=True, max_length=65535, null=True)),
                ('ph_yyyymmdd2', models.CharField(blank=True, max_length=50, null=True)),
                ('ph_desc2', models.CharField(blank=True, max_length=65535, null=True)),
            ],
            options={
                'db_table': 'app_lfphotos2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppLfprojects',
            fields=[
                ('pr_key', models.IntegerField(primary_key=True, serialize=False)),
                ('pr_desc', models.CharField(blank=True, max_length=150, null=True)),
                ('pr_address', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'app_lfprojects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppLfrepemails',
            fields=[
                ('repe_key', models.IntegerField(primary_key=True, serialize=False)),
                ('repe_fk_rep_key', models.IntegerField(blank=True, null=True)),
                ('repe_fk_emp_key', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_lfrepemails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppLfreportes',
            fields=[
                ('rep_key', models.IntegerField(primary_key=True, serialize=False)),
                ('rep_name', models.CharField(blank=True, max_length=80, null=True)),
                ('rep_fk_emp_key', models.IntegerField(blank=True, null=True)),
                ('rep_fk_emp_key_sup', models.IntegerField(blank=True, null=True)),
                ('rep_fk_pr_key', models.IntegerField(blank=True, null=True)),
                ('rep_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('rep_user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('rep_send', models.IntegerField(blank=True, null=True)),
                ('rep_send_email', models.CharField(blank=True, max_length=80, null=True)),
                ('rep_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('rep_yyyymmdd', models.CharField(blank=True, max_length=50, null=True)),
                ('rep_ws_to', models.CharField(blank=True, max_length=255, null=True)),
                ('rep_pages', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_lfreportes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('user_key', models.IntegerField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user_password', models.BinaryField(blank=True, null=True)),
                ('user_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('user_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('user_email', models.CharField(blank=True, max_length=50, null=True)),
                ('user_fk_cia_key', models.IntegerField(blank=True, null=True)),
                ('user_role', models.IntegerField(blank=True, null=True)),
                ('user_address', models.CharField(blank=True, max_length=100, null=True)),
                ('user_llave', models.CharField(blank=True, max_length=50, null=True)),
                ('user_celular', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.IntegerField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user_password', models.BinaryField(blank=True, null=True)),
                ('user_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('user_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('user_email', models.CharField(blank=True, max_length=50, null=True)),
                ('user_fk_cia_key', models.IntegerField(blank=True, null=True)),
                ('user_role', models.IntegerField(blank=True, null=True)),
                ('user_address', models.CharField(blank=True, max_length=100, null=True)),
                ('user_llave', models.CharField(blank=True, max_length=50, null=True)),
                ('user_celular', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Usuarios',
                'managed': False,
            },
        ),
    ]
